# UNIVERSITY OF SOUTHAMPTON

# FOR UNDERGRADUATE

In [3]:
pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\user\appdata\roaming\python\python311\site-packages (4.23.1)
Requirement already satisfied: urllib3<3,>=1.26 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.0.7)
Requirement already satisfied: trio~=0.17 in c:\users\user\appdata\roaming\python\python311\site-packages (from selenium) (0.26.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\user\appdata\roaming\python\python311\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2024.8.30)
Requirement already satisfied: typing_extensions~=4.9 in c:\users\user\appdata\roaming\python\python311\site-packages (from selenium) (4.12.2)
Requirement already satisfied: websocket-client~=1.8 in c:\users\user\appdata\roaming\python\python311\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\user\appdata\roaming\python\python311\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.16.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\user\appdata\roaming\python\python311\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

def initialize_webdriver(path: str) -> webdriver.Chrome:
    """
    Initializes the Chrome WebDriver.

    Args:
        path (str): The path to the ChromeDriver executable.

    Returns:
        webdriver.Chrome: The initialized Chrome WebDriver.
    """
    service = Service(path)  # Create a Service object
    driver = webdriver.Chrome(service=service)  # Initialize the WebDriver
    return driver  # Return the WebDriver instance

# Chrome webdriver
path = r"C:\Users\User\Downloads\chromedriver-win64\chromedriver-win64\chromedriver.exe"
driver = initialize_webdriver(path)

url = 'https://www.southampton.ac.uk/courses/undergraduate?keyword_filter='
driver.get(url)

# Find all elements with data-study-level attribute equal to 'ug_course_v1'
elements = driver.find_elements(By.XPATH, "//li[@data-study-level='ug_course_v1']")

# Find all course containers
wait = WebDriverWait(driver, 10)



# Initialize lists to store course details
course_names = []
degrees = []
durations =[]
course_links=[]

for element in elements:
    try:
        degree_element = element.find_element(By.CLASS_NAME, 'card-sub-title')
        degree=degree_element.text

    except:
        degree='NA'
    degrees.append(degree)

    try:
        course_name_element = element.find_element(By.CLASS_NAME, 'card-title')
        course_name=course_name_element.text

    except:
        degree='NA'
    course_names.append(course_name)

    try:
        duration_element = element.find_element(By.XPATH, ".//div[contains(text(), 'Duration:')]/span")
        duration = duration_element.text
    except:
        degree='NA'
    durations.append(duration)

    try:
        course_link_element = element.find_element(By.TAG_NAME, "a")
        course_link = course_link_element.get_attribute("href")
    except:
        course_link = "NA"
    course_links.append(course_link)



# Close the webdriver
driver.quit()

# Create a dataframe
data = {
    "Course_Title": course_names,
    "Degree_Type": degrees,
    "Duration":durations,
    "Course_Link": course_links
}

df1 = pd.DataFrame(data)

# Print the dataframe
df1

,Course_Title,Degree_Type,Duration,Course_Link
0,Accounting and Finance,BSc,3 years,https://www.southampton.ac.uk/courses/accounti...
1,Accounting and Finance with Placement Year,BSc,4 years,https://www.southampton.ac.uk/courses/accounti...
2,Accounting and Finance with Study Abroad Year,BSc,4 years,https://www.southampton.ac.uk/courses/accounti...
3,Accounting and Taxation,BSc,3 years,https://www.southampton.ac.uk/courses/accounti...
4,Accounting and Taxation with Placement Year,BSc,4 years,https://www.southampton.ac.uk/courses/accounti...
...,...,...,...,...
244,Software Engineering,BEng,3 years,https://www.southampton.ac.uk/courses/software...
245,Sustainable Luxury (Textiles),BA,3 years,https://www.southampton.ac.uk/courses/sustaina...
246,Textile Design,BA,3 years,https://www.southampton.ac.uk/courses/textile-...
247,Zoology,MSci,4 years,https://www.southampton.ac.uk/courses/zoology-...
248,Zoology,BSc,3 years,https://www.southampton.ac.uk/courses/zoology-...

# FOR POSTGRADUATE

In [17]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

#Chrome webdriver
# driver = webdriver.Chrome()
def initialize_webdriver(path: str) -> webdriver.Chrome:
    """
    Initializes the Chrome WebDriver.

    Args:
        path (str): The path to the ChromeDriver executable.

    Returns:
        webdriver.Chrome: The initialized Chrome WebDriver.
    """
    service = Service(path)  # Create a Service object
    driver = webdriver.Chrome(service=service)  # Initialize the WebDriver
    return driver  # Return the WebDriver instance

url = 'https://www.southampton.ac.uk/courses/postgraduate?keyword_filter='
driver.get(url)

# Find all elements with data-study-level attribute equal to 'ug_course_v1'
elements = driver.find_elements(By.XPATH, "//li[@data-study-level='pg_course']")

# Find all course containers
wait = WebDriverWait(driver, 10)



# Initialize lists to store course details
course_names = []
degrees = []
typical_offers = []
durations =[]
course_links=[]


for element in elements:
    try:
        degree_element = element.find_element(By.XPATH, ".//div[@class='leading-none text-black font-semibold md:text-xl']")
        degree=degree_element.text

    except:
        degree='NA'
    degrees.append(degree)

    try:
        course_name_element = element.find_element(By.CLASS_NAME, 'card-title')
        course_name=course_name_element.text

    except:
        degree='NA'
    course_names.append(course_name)

    try:
        duration_element = element.find_element(By.XPATH, ".//div[contains(text(), 'Duration:')]/span")
        duration = duration_element.text
    except:
        degree='NA'
    durations.append(duration)

    try:
        course_link_element = element.find_element(By.TAG_NAME, "a")
        course_link = course_link_element.get_attribute("href")
    except:
        course_link = "NA"
    course_links.append(course_link)



# Close the webdriver
driver.quit()

# Create a dataframe
data = {
    "Course_Title": course_names,
    "Degree_Type": degrees,
    "Duration":durations ,
    "Course_Link":course_links
}

df2 = pd.DataFrame(data)

# Print the dataframe
df2

MaxRetryError: HTTPConnectionPool(host='localhost', port=54103): Max retries exceeded with url: /session/841ae203486680b9b5040a5dcb8155f3/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002298FD335D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

# CSV FILE

In [ ]:
# Concatenate the DataFrames vertically
combined_df = pd.concat([df1, df2])

# Save the combined DataFrame to a CSV file
combined_df.to_csv('UniversityOfSouthampton.csv', index=False)

In [11]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By

def initialize_webdriver(path: str) -> webdriver.Chrome:
    """
    Initializes the Chrome WebDriver.

    Args:
        path (str): The path to the ChromeDriver executable.

    Returns:
        webdriver.Chrome: The initialized Chrome WebDriver.
    """
    service = Service(path)  # Create a Service object
    driver = webdriver.Chrome(service=service)  # Initialize the WebDriver
    return driver  # Return the WebDriver instance

# Chrome webdriver
path = r"C:\Users\User\Downloads\chromedriver-win64\chromedriver-win64\chromedriver.exe"
driver = initialize_webdriver(path)

url = 'https://www.southampton.ac.uk/courses/undergraduate?keyword_filter='
driver.get(url)

# Find all elements with data-study-level attribute equal to 'ug_course_v1'
elements = driver.find_elements(By.XPATH, "//li[@data-study-level='ug_course_v1']")

# Fetch course details
course_names, degrees, durations, course_links = fetch_course_details(elements)

# Close the webdriver
driver.quit()

# Create a dataframe
data = {
    "Course_Title": course_names,
    "Degree_Type": degrees,
    "Duration": durations,
    "Course_Link": course_links
}

df1 = pd.DataFrame(data)

# Print the dataframe
df1

,Course_Title,Degree_Type,Duration,Course_Link
0,Accounting and Finance,BSc,3 years,https://www.southampton.ac.uk/courses/accounti...
1,Accounting and Finance with Placement Year,BSc,4 years,https://www.southampton.ac.uk/courses/accounti...
2,Accounting and Finance with Study Abroad Year,BSc,4 years,https://www.southampton.ac.uk/courses/accounti...
3,Accounting and Taxation,BSc,3 years,https://www.southampton.ac.uk/courses/accounti...
4,Accounting and Taxation with Placement Year,BSc,4 years,https://www.southampton.ac.uk/courses/accounti...
...,...,...,...,...
244,Software Engineering,BEng,3 years,https://www.southampton.ac.uk/courses/software...
245,Sustainable Luxury (Textiles),BA,3 years,https://www.southampton.ac.uk/courses/sustaina...
246,Textile Design,BA,3 years,https://www.southampton.ac.uk/courses/textile-...
247,Zoology,MSci,4 years,https://www.southampton.ac.uk/courses/zoology-...
248,Zoology,BSc,3 years,https://www.southampton.ac.uk/courses/zoology-...